# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  # aquacity:
  #   image: aquacity
  #   build:
  #     context: .
  #     dockerfile: aquacity/Dockerfile
  #   ports:
  #     - 8080:8080
  db:
    image: postgres:14-alpine
    container_name: aquacity-db
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'aquacity'
    ports:
      - '5432:5432'
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
    networks:
      - aquacity-network

networks:
  aquacity-network:  
